# Generated by Django 5.2.1 on 2025-05-10 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOwner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectowner',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='projectowner',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='projectowner',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='projectowner',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectowner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
