# Generated by Django 5.2.1 on 2025-05-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOwner', '0002_remove_projectowner_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectowner',
            name='terms_agreed',
            field=models.TextField(blank=True),
        ),
    ]
