# Generated by Django 5.2.1 on 2025-05-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOwner', '0003_projectowner_terms_agreed'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectowner',
            name='id_card_picture',
            field=models.ImageField(blank=True, null=True, upload_to='owners/id_cards/'),
        ),
    ]
